### ISSUE TITLE
Todo list for first release 

### ISSUE THREAD

**Issue by Peyman-N** [openMetadataInitiative/bids2openminds#56]
TODO for tool:

- [x] uploading the bids2openminds data to KG:
       conversion to fairgraph objects was successful but last upload caused the kg-ppd to crash. Probably caused by trying to upload file and file repository to KG.
- [x]  Pull request #50 seems good, juste need final validation from @apdavison  or @lzehl , but it should merged last.
- [x] Pull request #51 , still some bugs need to be solved. 
- [x] Pull request #52 , seems good but neeeds a function needs a test.
- [x] Pull request #53, seems good but needs to use try expect.
- [x] Pull request #58
- [x] Pul request #59 
- [x] Pull request #9
